### ISSUE TITLE
Should the failsafe destroy thread be detached?

### ISSUE THREAD

**Issue by NiLuJe** [geek1011/NickelMenu#17]
AFAIK, the default state of a pthread is joined.

Not waiting for it means it "leaks" on termination.

Should we make it detached to take care of that, or am I missing some Qt quirk?

(I can take care of & test that, just wanted to double-check first ;)).

**Comment by geek1011** [comment]
Yes, it seems I overlooked that earlier.

**Comment by NiLuJe** [comment]
Cool, I'll give it a go after dinner ;).
