### ISSUE TITLE
wifi toggle

### ISSUE THREAD

**Issue by ssd2** [geek1011/NickelMenu#25]
I'd like an action to toggle Nickel's idea of wifi state.
I don't mean turning off the interface (ifconfig down) but actually disabling it (or I suppose enabling it) like the icon was tapped from the home screen and the slider moved...

I'd love to be able to get to this from the reading screen without popping all the way back to the home screen.

Would this be possible?  If so, my kobo's battery would thank you!!

**Comment by ssd2** [comment]
If the slider can't be toggled, I'd be almost has happy with either the wifi popup or the wifi settings screen, or even just the regular settings screen from which I could get to wifi settings.

**Comment by ssd2** [comment]
Possibly related
 [FeatureSettings]
 AIRPLANE_MODE=true

**Comment by geek1011** [comment]
Also MR:post-3985234
