### ISSUE TITLE
menu hopping

### ISSUE THREAD

**Issue by ssd2** [geek1011/NickelMenu#26]
One of my greatest irritations in latest firmwares is the removal of the "home" button from the reading screen.  Sometimes I have to hit return two or three times to get back to home.

Would it be possible to add items from the home screen menu (like home, my books, my articles, settings) so they could be added to the reading overflow menu?

**Comment by geek1011** [comment]
I'll look into that. My only concern with doing this is how it will interact with Nickel's reading session management, so I'll need to check how that works and if MainWindowController handles everything as needed.

**Comment by geek1011** [comment]
OK, this will be doable (EventEngine::endReadingSession is called by ReadingController::viewWillDisappear, which is an implementation of AbstractController::viewWillDisappear).

**Comment by ssd2** [comment]
Ironically, you added everything _except_ what I asked for -- a link to the home screen.

Not to be ungrateful, I think this change is actually wonderful, and although I'd still like to have HOME still, with all these other options, I'm not sure I'd ever use it!!   Thanks!

**Comment by geek1011** [comment]
Oh, I guess I misinterpreted the question. I'll add a home option for the next version, although it'll be part of `nickel_misc` rather than `nickel_open` for technical reasons.
