### ISSUE TITLE
Ignore editor temp files

### ISSUE THREAD

**Issue by geek1011** [geek1011/NickelMenu#27]
MR:post-3992019

**Comment by geek1011** [comment]
- Nano: `*.swp`
- Vim: `*~`, `*.swp`, `*.swo` (it can also create more sequential extensions, but those aren't likely to happen anyways)
- Gedit: `*~`

Any others?

**Comment by geek1011** [comment]
I should probably also exclude OS-specific files too:

- macOS: `.DS_Store*`, `.Spotlight-V*`, `._*`
- Windows: `thumbs.db`, `Thumbs.db`, `desktop.ini`

**Comment by NiLuJe** [comment]
Kate does `.${file}.kate-swp` (i.e., besides the extension, it also makes it hidden).

**Comment by geek1011** [comment]
I think I'll exclude all dotfiles, the Windows stuff, and stuff ending with a `~` or `#`.

**Comment by shermp** [comment]
Wouldn't it have been easier to have a defined config format? Either a custom extension, and/or file signature?

Something like `config.nm`?

**Comment by geek1011** [comment]
That was my original plan, but I realized it would be easier for Windows users if I allowed any extension (most don't know how to rename files to / save files under different extensions, and many don't even know files have extensions).
