### ISSUE TITLE
Improved nickel_extras:web_browser action

### ISSUE THREAD

**Issue by geek1011** [geek1011/NickelMenu#49]
- Option to show in a modal instead of fullscreen.
- Option to load a custom URL.
- Option to add a custom CSS override.

---

I've figured out the issue with the original attempt I abandoned a while ago:

https://github.com/geek1011/NickelMenu/blob/50c7374fcf8c86fe809129a4a10def601ecfe248/src/action_cc.cc#L319-L334

When it isn't already connected to a network, `BrowserWorkflowManager::openBrowser` will use the `WirelessWorkflowManager` `sharedInstance` to start the connection and attach a one-time (it removes itself after) signal handler which runs `BrowserWorkflowManager::openBrowserAfterConnected` on success (`InternetProvider::internetIsAccessible`). The thing is, it stores the state information in the `BrowserWorkflowManager` instance, and passes the pointer to it as-is to the signal handler.

Since my original attempt allocated the objects on the stack, this meant that it would try and dereference an invalid stack pointer after the connection succeeds. To fix this, all we need to do is allocate the `BrowserWorkflowManager` and the function arguments on the heap.

**Comment by shermp** [comment]
Oooh, custom CSS? Because the stock styling is terrible in many respects.

**Comment by geek1011** [comment]
Yes, you can try it if you build the WIP PR from source and change the last QString.

**Comment by shermp** [comment]
Now... if only I can figure out how to make some nice looking form elements... Especially checkboxes, because the current ones don't scale properly.

**Comment by geek1011** [comment]
I'll probably want to see if I can hide scrollbars, since they break the renderer.

**Comment by shermp** [comment]
Actually, an option to prevent scrolling would also be awesome, if possible.

**Comment by geek1011** [comment]
Just do `* {overflow: hidden !important}` as the CSS.
