### ISSUE TITLE
NickelMenu v0.2.0 error in nickel_setting screenshot confirmation pop-up

### ISSUE THREAD

**Issue by jackiew1** [geek1011/NickelMenu#61]
Although this config entry works:

```menu_item : main : * Screenshots on : nickel_setting : enable : screenshots```

it has an error in the confirmation pop-up message. I assume it should say something like `enabled screenshots` but instead it's `enabled enable`. Similarly the disable screenshots option pops up `disabled disable`

**Comment by geek1011** [comment]
I forgot to switch `arg1` and `arg2`. I'll fix this and release it next week. Thanks.
